name: Sphinx Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # You may pin to the exact commit or the version.

jobs:
  build_doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
 
      - name: Sphinx Build
        # You may pin to the exact commit or the version.
        # uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2
        uses: ammaraskar/sphinx-action@0.4
        with:
          # The folder containing your sphinx docs.
          docs-folder: docs/sphinx_project # default is docs/
          # The command used to build your documentation.
          build-command: make html # optional, default is make html
          # Run before the build command, you can use this to install system level dependencies, for example with "apt-get update -y && apt-get install -y perl"
          pre-build-command:  python conf.py # optional


      - name: build the docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_unix.txt
          cd docs/sphinx_project

          #clean up:
          make clean;

          #make doku
          ##configurations
          sphinx-apidoc -o _source ../../ensembler

          cp ../../examples/Tutorial*ipynb ./Tutorials
          cp ../../examples/Example*ipynb ./Examples
          
          mkdir _build
          python conf.py
          
          echo ${PWD}
          ls .
          ls ./*
          
          ##execute making docu
          make html

          cp -r _build/hmtl/*  ../

     
