name: Sphinx Build
  on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # You may pin to the exact commit or the version.

  jobs:
    build_doc:
      runs-on: ubuntu-latest
      strategy:
      python-version: 3.7

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:

        - name: build the docs
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements_unix.txt
            cd docs/sphinx_project

            #clean up:
            make clean;

            #make doku
            ##configurations
            sphinx-apidoc -o _source ../../ensembler

            cp ../../examples/Tutorial*ipynb ./Tutorials
            cp ../../examples/Example*ipynb ./Examples

            python conf.py

            ##execute making docu
            make html

            cp -r _build/hmtl/*  ../
