name: Sphinx Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # You may pin to the exact commit or the version.

jobs:
  build_doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
    
      - name: build the docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_unix.txt
          cd docs/sphinx_project

          #clean up:
          make clean;

          #make doku
          ##configurations
          sphinx-apidoc -o _source ../../ensembler

          cp ../../examples/Tutorial*ipynb ./Tutorials
          cp ../../examples/Example*ipynb ./Examples

          python conf.py
          
          echo ${PWD}
          ls .
          ls ./*
          less Makefile
          
          ##execute making docu
          make html ${PWD}

          cp -r _build/hmtl/*  ../
