name: CI

on:
  push:
    branches:
      - "cookiecutter"
  pull_request:
    branches:
      - "master"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Configure conda
      run: |
        conda activate
        conda config --add channels conda-forge
        conda config --set always_yes True
        conda install conda conda-build
        conda update --quiet --all
      env:
        OPERATING_SYSTEM: ${{ matrix.os }}

    - name: Create test environment
      shell: bash
      run: |
        conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=${{ matrix.python-version }} devtools/conda-envs/test_env.yaml

    - name: Install package
      shell: bash -l {0}
      run: |
        conda activate test
        python setup.py develop --no-deps

    - name: Run tests

      # conda setup requires this special shell
      shell: bash -l {0}

      run: |
        pytest -v --cov=ensembler --cov-report=xml --color=yes ensembler/tests/

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
